
spring:
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVER:127.0.0.1:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.mdymen.skiplocked.kafka.consumer.EventDeserializer
      group-id: group
    topic: ${TOPIC:skiplocked-topic}
  datasource:
    driver-classe-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:skiplocked}?allowPublicKeyRetrieval=true&autoReconnect=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:mdymen_pass}
  jpa:
    show-sql: true
  main:
    allow-circular-references: true
  application:
    name: kafka.consumer

server:
  port: 8092